export const FETCH_TRANSLATION_START = 'FETCH_TRANSLATION_START';
export const FETCH_TRANSLATION_SUCCESS = 'FETCH_TRANSLATION_SUCCESS';
export const FETCH_TRANSLATION_FAILURE = 'FETCH_TRANSLATION_FAILURE';

export const POST_TRANSLATION_START = 'POST_TRANSLATION_START';
export const POST_TRANSLATION_SUCCESS = 'POST_TRANSLATION_SUCCESS';
export const POST_TRANSLATION_FAILURE = 'POST_TRANSLATION_FAILURE';

export const SHOW_BUTTON = 'SHOW_BUTTON';
