export const FETCH_TRANSLATION_START = 'FETCH_TRANSLATION_START';
export const FETCH_TRANSLATION_SUCCESS = 'FETCH_TRANSLATION_SUCCESS';
export const FETCH_TRANSLATION_FAILURE = 'FETCH_TRANSLATION_FAILURE';

export const POST_TRANSLATION_START = 'POST_TRANSLATION_START';
export const POST_TRANSLATION_SUCCESS = 'POST_TRANSLATION_SUCCESS';
export const POST_TRANSLATION_FAILURE = 'POST_TRANSLATION_FAILURE';

export const BUTTON_CLICKED = 'BUTTON_CLICKED';

export const FETCH_DATA_START = 'FETCH_DATA_START';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';

export const FETCH_DATA_BY_ID_SUCCESS = 'FETCH_DATA_BY_ID_SUCCESS';
export const FETCH_DATA_BY_ID_FAIL = 'FETCH_DATA_BY_ID_FAIL';

export const DELETE_DATA_START = 'DELETE_DATA_START';
export const DELETE_DATA_SUCCESS = 'DELETE_DATA_SUCCESS';
export const DELETE_DATA_FAIL = 'DELETE_DATA_FAIL';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
